### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by tunnckoCore**
- total refactor
- faster loops
- smarter checks
- add callback api
- lower code
- tests
- remove cli (we can do `jscss-cli`)
- remove dependencies - not needed, if someone need they will download them

### CODE REVIEW

**Comment by arselzer** [comment]
Hi, thanks for spending time to improve jscss.

Merging these changes will break compatibility, and it seems like a few people are using this project, so I would rather not merge this into master right away, and take some time to reconsider the structure of everything, possibly making some more changes, before releasing a new version.

Firstly, I think removing cssbeautify is a good idea, since it keeps this module simple, doing only what it needs to.

You added a callback API, but what is the point of it? jscss does not open any files, do network I/O, or compute stuff on a GPU. It will just execute JS and process strings, blocking the event loop anyway. This would make sense though if there is some kind of include mechanism (like LESS).

I think a speed test should be added. Did you measure the speed improvement?

Also, I'm not sure if removing the binary is good, except making this just a library. It just takes up 4KB, and most people will like the convenience. It also makes integrating jscss into package.json build scripts much easier. jscss-cli is a bad name. Something like jscssc maybe, but why not keep `jscss`, it shouldn't cause any collisions with existing binaries?

And while we're at it, I'll list some things that have been bothering me or that would be nice additions for this huge version jump:
- The huge regex. It would be nice to build a robust parser/lexer, sadly I just don't have any experience with parsers.
- The collision of of the pipe symbol -  `|` - and both a [valid CSS selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) and the bitwise or in JS. jscss should be compatible with all JS and css. It would suck if someone pastes in CSS using the selector and everything fails.

**Comment by tunnckoCore** [comment]
> You added a callback API, but what is the point of it?

Sometimes it's needed to have. it's not a problem to have and it is normal, we are in nodeland.

> I think a speed test should be added. Did you measure the speed improvement?

while is faster than shitty foreach. Also we (you) should consider that change `vm` to something with `new Function` for easy browser compatibility port.

> Also, I'm not sure if removing the binary is good

it's a trend, and keep separate logics, save bandwidth, install, `require`-ing and many more things. 
The CLI should be separate package, becase if it is,it would have free space for better CLI and options or so on.

Actually, this module cant be more than that, it's not worth to invest so time. And @regexps are pretty slow. For parser and compilier, yea maybe. But not with that name and to that way.
Or try @jonschlinkert's www.npm.im/snapdragon :)

Actually I started to just fix `index.js` requires (look [index.js#L1-L2](https://github.com/AlexanderSelzer/jscss/blob/master/index.js#L1-L2), you should add `./lib/`), because we building @jstransformers([-jscss](https://github.com/jstransformers/jstransformer-jscss)) and it didn't work. 

I'll just release it with some other name and won't update it. :)

**Comment by arselzer** [comment]
Btw, merged it into the `v3` branch.

> it's not a problem to have and it is normal, we are in nodeland.
> Agreed, it's not a problem, should be fine to keep.
> 
> while is faster than shitty foreach. Also we (you) should consider that change vm to something with new Function for easy browser compatibility port.

forEach should be max 2-4 times slower, the number of iterations is probably under 10.000. The concatenations and regexes will probably take a few magnitudes more time, but let's not fight over that :smile: .

`vm` is beneficial, because the primary purpose of this is preprocessing CSS on the server, at least that's what I thought. A CSS preprocessor just shouldn't be able to execute anything on a server, you never know how people use it. Detecting the environment and switching between eval and vm is easily done. In fact the first version of this was actually using eval.

About removing the binary, yes, of course it will save space, bandwidth, but is it worth it sacrificing the convenience for 100KB? I agree that separation is good, but look at `less` for example, everything is included and it works well. I will still keep the "binary".

**Comment by tunnckoCore** [comment]
Okey, thanks!

Beside that, you should update your index.js from

``` js
var convert = require("./convert");
var compile = require("./compile");
```

to

``` js
var convert = require("./lib/convert");
var compile = require("./lib/compile");
```

because package not works currently. and get the tests from this PR

**Comment by arselzer** [comment]
Thanks, will immediately fix that. Weird that I never noticed.

**Comment by tunnckoCore** [comment]
@AlexanderSelzer because you dont have tests :) and CI process

**Comment by tunnckoCore** [comment]
btw, publish it to npm as `0.3.0` :)

**Comment by arselzer** [comment]
:smile: a CI process for something like this, hehe, I didn't really expect anyone to use it :P

Published it as 0.2.3 for now, 0.3 (the branch with your changes) is not merged with master yet, I'll probably add some more changes, but will publish it soon.

Any suggestions for 1.0.0?

**Comment by tunnckoCore** [comment]
doh... please follow semver. it cant be `0.2.3`. you're in javascript land (nodejs) node-land.

> Any suggestions for 1.0.0?

No. I give my try and comment already. :)

**Comment by arselzer** [comment]
npm accepted it, so it can be. It's just a (pretty bad) bug fix.

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable. (semver.org)

**Comment by tunnckoCore** [comment]
but it's actually breaking change, because it didn't work in the `0.2.2`

nevermind, it won't change that `semver` sucks. LOL

**Pull request closed without merging**
